title: Title 2
author: Nathan Neff
email: nate@nateneff.com
description: > # this means to ignore newlines until "baseurl:"
  Description is here

# social links
github_username:  NathanNeff

show_excerpts: true # set to false to remove excerpts on the homepage
